# Generated by Django 5.1.1 on 2024-09-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='color',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='model',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
