# Generated by Django 5.1.1 on 2024-09-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogpost_color_blogpost_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='color',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='model',
        ),
    ]
